VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty32"
	config.vm.provider :virtualbox do |virtualbox|

        virtualbox.customize [

            "modifyvm", :id,
            "--memory", "256",
            "--cpus", "1",
            "--hwvirtex", "off",
            "--pae", "on",
            "--ioapic", "off",
            "--natdnsproxy1", "on",
            "--natdnshostresolver1", "on"

        ]

	end

    config.vm.define :howto do |howto_config|

        howto_config.vm.hostname = "howto"
        howto_config.vm.boot_timeout = 600
        howto_config.vm.synced_folder "sample.backup", "/home/vagrant/backup"

        howto_config.vm.provision :shell, :path => "shell/set_timezone.sh"
		howto_config.vm.provision :puppet do |puppet|

            puppet.manifests_path = "puppet/manifests/"
			puppet.module_path = [ "puppet/modules", "puppet/librarian/modules" ]
			puppet.manifest_file = "default.pp"

            puppet.facter = {
                # Specifying the LANG environment variable this way is a work around.
                "hack=hack LANG=en_US.UTF-8 hack" => "hack"
            }

		end

    end

end
